# Generated by Django 5.2.11 on 2026-02-10 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('notes', '0006_flashcarddeck_flashcard_flashcardreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('file_replaced', 'File Replaced'), ('restored', 'Restored')], default='edited', max_length=20)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='note_versions/%Y/%m/')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_versions', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notes.note')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.subject')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('note', 'version_number')},
            },
        ),
    ]
