# Generated by Django 5.2.11 on 2026-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_noteversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_handwritten',
            field=models.BooleanField(default=False, help_text='Whether this note is a scanned/photographed handwritten note'),
        ),
        migrations.AddField(
            model_name='note',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text='Average OCR confidence score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='ocr_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', help_text='Status of OCR text extraction', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Text extracted via OCR'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('ppt', 'PPT'), ('pptx', 'PPTX'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG')], max_length=10),
        ),
    ]
