# Generated by Django 5.2.11 on 2026-02-10 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_is_handwritten_note_ocr_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_type', models.CharField(choices=[('clarification', 'Clarification'), ('example', 'Example'), ('explanation', 'Alternate Explanation'), ('summary', 'Summary'), ('correction', 'Correction'), ('resource', 'Additional Resource')], default='clarification', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_layers', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='notes.note')),
            ],
            options={
                'ordering': ['-is_pinned', '-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteLayerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='notes.notelayer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('layer', 'user')},
            },
        ),
    ]
