# Generated by Django 5.2.11 on 2026-02-10 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('notes', '0009_notelayer_notelayervote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Total seconds spent in this session')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_ping_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Calendar date of the session (for daily aggregation)')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='notes.note')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='academics.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='notes_study_user_id_2a4b07_idx'), models.Index(fields=['user', 'subject'], name='notes_study_user_id_67a57b_idx')],
            },
        ),
    ]
