# Generated by Django 5.2.11 on 2026-02-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Auto-generated summary of the note'),
        ),
        migrations.AddField(
            model_name='note',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the summary was last generated', null=True),
        ),
    ]
