# Generated by Django 5.2.11 on 2026-02-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_topperverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='highlight_color',
            field=models.CharField(blank=True, default='', help_text='Color tag: yellow, green, blue, red, purple, or empty', max_length=20),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='is_offline',
            field=models.BooleanField(default=False, help_text='Whether the user has saved this note for offline reading'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='personal_note',
            field=models.TextField(blank=True, help_text='Personal notes or highlights for this bookmark', max_length=2000),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
