# Generated by Django 5.2.11 on 2026-02-10 11:22

from django.db import migrations


BADGES = [
    # Upload milestones
    {
        'slug': 'first-upload',
        'name': 'First Upload',
        'description': 'Uploaded your very first note',
        'icon': 'Upload',
        'color': '#10B981',
        'category': 'upload',
        'threshold_field': 'upload_count',
        'threshold_value': 1,
        'points_reward': 15,
        'sort_order': 1,
    },
    {
        'slug': 'five-uploads',
        'name': 'Prolific Contributor',
        'description': 'Uploaded 5 approved notes',
        'icon': 'FolderUp',
        'color': '#3B82F6',
        'category': 'upload',
        'threshold_field': 'upload_count',
        'threshold_value': 5,
        'points_reward': 25,
        'sort_order': 2,
    },
    {
        'slug': 'ten-uploads',
        'name': 'Note Machine',
        'description': 'Uploaded 10 approved notes',
        'icon': 'Rocket',
        'color': '#8B5CF6',
        'category': 'upload',
        'threshold_field': 'upload_count',
        'threshold_value': 10,
        'points_reward': 50,
        'sort_order': 3,
    },
    {
        'slug': 'twenty-five-uploads',
        'name': 'Knowledge Vault',
        'description': 'Uploaded 25 approved notes',
        'icon': 'Library',
        'color': '#F59E0B',
        'category': 'upload',
        'threshold_field': 'upload_count',
        'threshold_value': 25,
        'points_reward': 100,
        'sort_order': 4,
    },
    # Download milestones
    {
        'slug': 'ten-downloads',
        'name': 'Helpful Notes',
        'description': 'Your notes were downloaded 10 times',
        'icon': 'Download',
        'color': '#06B6D4',
        'category': 'download',
        'threshold_field': 'downloads_received',
        'threshold_value': 10,
        'points_reward': 20,
        'sort_order': 10,
    },
    {
        'slug': 'fifty-downloads',
        'name': 'Popular Author',
        'description': 'Your notes were downloaded 50 times',
        'icon': 'TrendingUp',
        'color': '#EC4899',
        'category': 'download',
        'threshold_field': 'downloads_received',
        'threshold_value': 50,
        'points_reward': 50,
        'sort_order': 11,
    },
    {
        'slug': 'hundred-downloads',
        'name': '100 Downloads',
        'description': 'Your notes were downloaded 100 times',
        'icon': 'Flame',
        'color': '#EF4444',
        'category': 'download',
        'threshold_field': 'downloads_received',
        'threshold_value': 100,
        'points_reward': 100,
        'sort_order': 12,
    },
    {
        'slug': 'five-hundred-downloads',
        'name': 'Semester Star',
        'description': 'Your notes were downloaded 500 times',
        'icon': 'Star',
        'color': '#F59E0B',
        'category': 'download',
        'threshold_field': 'downloads_received',
        'threshold_value': 500,
        'points_reward': 250,
        'sort_order': 13,
    },
    # Engagement milestones
    {
        'slug': 'first-comment',
        'name': 'Conversationalist',
        'description': 'Posted your first comment',
        'icon': 'MessageSquare',
        'color': '#10B981',
        'category': 'engagement',
        'threshold_field': 'comments_count',
        'threshold_value': 1,
        'points_reward': 5,
        'sort_order': 20,
    },
    {
        'slug': 'ten-comments',
        'name': 'Active Discusser',
        'description': 'Posted 10 comments',
        'icon': 'MessagesSquare',
        'color': '#6366F1',
        'category': 'engagement',
        'threshold_field': 'comments_count',
        'threshold_value': 10,
        'points_reward': 20,
        'sort_order': 21,
    },
    {
        'slug': 'fifty-comments',
        'name': 'Community Pillar',
        'description': 'Posted 50 comments',
        'icon': 'Users',
        'color': '#D946EF',
        'category': 'engagement',
        'threshold_field': 'comments_count',
        'threshold_value': 50,
        'points_reward': 50,
        'sort_order': 22,
    },
]


def seed_badges(apps, schema_editor):
    Badge = apps.get_model('gamification', 'Badge')
    for data in BADGES:
        Badge.objects.update_or_create(slug=data['slug'], defaults=data)


def remove_badges(apps, schema_editor):
    Badge = apps.get_model('gamification', 'Badge')
    Badge.objects.filter(slug__in=[b['slug'] for b in BADGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_badges, remove_badges),
    ]
