# Generated by Django 5.2.11 on 2026-02-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_seed_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='five_star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='ratings_received',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
